# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

<<<<<<< HEAD
ifneq ($(filter evert,$(TARGET_DEVICE)),)
=======
ifneq ($(filter beckham chef evert lake payton,$(TARGET_DEVICE)),)
>>>>>>> 089f700... sdm660-family: Switch to standalone extract utils

endif
